services:
  sfu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pion-sfu
    restart: always
    ports:
      - "50000-50100:50000-50100/udp"
    expose:
      - "8080"
    networks:
      - shared

networks:
  shared:
    external: true
